excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://satyadeepk.github.io
title: Satyadeep K
tagline: A log of everyday life
description: My awesome new site
paginate: 5
permalink: /:year/:month/:title/
include: ["_pages"]
