excerpt_separator: ""
markdown: kramdown
url: http://satyadeepk.github.io
title: Satyadeep K
tagline: My passions, Tech and Photography
description: My passions, Tech and Photography
paginate: 5
permalink: /:year/:month/:title/
include: ["_pages"]

theme: jekyll-theme-slate